// Builds the chartai engine into one readable ES module with the GPU worker inlined.
//
//   bun run build.ts             -> writes ../wwwroot/chartai.js
//   bun run build.ts <outfile>   -> writes the given file instead
//   CHARTAI_MINIFY_SHADERS=0     -> keep the WGSL sources verbatim (comments, newlines)
//
// Mirrors the "chart-library with inline worker" part of upstream chartai's build.ts
// (https://github.com/dgerrells/chartai): the worker is bundled standalone and minified,
// embedded as a string, and the library is bundled unminified without code splitting so the
// output is one self-contained file. Needs nothing but Bun (no node_modules).
import path from "path";
import fs from "fs";

const ROOT = import.meta.dir;
const SRC = path.join(ROOT, "src");
const OUT = path.resolve(ROOT, process.argv[2] ?? path.join("..", "wwwroot", "chartai.js"));
const TMP = path.join(ROOT, ".build");
const MINIFY_SHADERS = process.env.CHARTAI_MINIFY_SHADERS !== "0";

// Strip comments and whitespace from the WGSL template strings of a src/shaders/**.ts source
// (same rules as upstream).
function minifyShaders(source: string): string {
  return source.replace(
    /(export const \w+ = `)([^`]+)(`)/g,
    (_m: string, prefix: string, shader: string, suffix: string) => {
      let s = shader;
      s = s.replace(/\/\/.*$/gm, "");
      s = s.replace(/\/\*[\s\S]*?\*\//g, "");
      s = s.replace(/^[ \t]+|[ \t]+$/gm, "");
      s = s.replace(/\n+/g, " ");
      s = s.replace(/ +/g, " ");
      s = s.replace(/ *([{}();,]) */g, "$1");
      return prefix + s.trim() + suffix;
    },
  );
}

// Every .ts source goes through this hook. Line endings are normalized so a CRLF checkout
// (git autocrlf on Windows) yields the same bundle as an LF one: template literals, i.e. the
// WGSL shaders, would otherwise carry the \r into the output. The shader check is done on the
// path inside the callback because Bun matches onLoad filters against native paths, which use
// backslashes on Windows.
const sourcePlugin = {
  name: "chartai-sources",
  setup(build: any) {
    build.onLoad({ filter: /\.ts$/ }, async (args: any) => {
      let source = (await Bun.file(args.path).text()).replace(/\r\n?/g, "\n");
      const parts = path.normalize(args.path).split(path.sep);
      if (MINIFY_SHADERS && parts.includes("shaders")) source = minifyShaders(source);
      return { contents: source, loader: "ts" };
    });
  },
};

const plugins = [sourcePlugin];

// Bun emits a duplicate `export { ChartManager };` in some versions (bun #5344, #10631).
function fixBunExportBug(file: string) {
  let content = fs.readFileSync(file, "utf-8");
  content = content.replace(/\nexport\s*{\s*ChartManager\s*};\s*\n/g, "\n");
  fs.writeFileSync(file, content);
}

async function buildInlineWorker(): Promise<string> {
  const outDir = path.join(TMP, "worker");
  fs.mkdirSync(outDir, { recursive: true });
  const result = await Bun.build({
    entrypoints: [path.join(SRC, "gpu-worker.ts")],
    outdir: outDir,
    format: "esm",
    minify: true,
    splitting: false, // the worker runs from a Blob URL and must be self-contained
    plugins,
  });
  if (!result.success) {
    console.error(result.logs);
    throw new Error("worker build failed");
  }
  const code = fs.readFileSync(path.join(outDir, "gpu-worker.js"), "utf-8");
  console.log(`worker: ${(code.length / 1024).toFixed(1)} KB (minified, inlined)`);
  return `// Auto-generated by build.ts - DO NOT EDIT\nexport const WORKER_CODE = ${JSON.stringify(code)};\n`;
}

async function buildLibrary() {
  fs.rmSync(TMP, { recursive: true, force: true });
  const inlinePath = path.join(SRC, "worker-inline.ts");
  fs.writeFileSync(inlinePath, await buildInlineWorker());
  try {
    const outDir = path.join(TMP, "lib");
    fs.mkdirSync(outDir, { recursive: true });
    const result = await Bun.build({
      entrypoints: [path.join(SRC, "index.ts")],
      outdir: outDir,
      format: "esm",
      minify: false,
      splitting: false,
      plugins,
    });
    if (!result.success) {
      console.error(result.logs);
      throw new Error("library build failed");
    }
    const built = path.join(outDir, "index.js");
    fixBunExportBug(built);
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.copyFileSync(built, OUT);
    console.log(`library: ${(fs.statSync(OUT).size / 1024).toFixed(1)} KB -> ${OUT}`);
  } finally {
    fs.rmSync(inlinePath, { force: true });
    fs.rmSync(TMP, { recursive: true, force: true });
  }
}

await buildLibrary();
